services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=
      - DB_PORT=
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=
      - JWT_SECRET=
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_FROM=
      - FRONTEND_URL=
      - AWS_REGION=
      - AWS_BUCKET=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_ENDPOINT=
      - SESSION_SECRET=
      - YANDEX_CLIENT_ID=
      - YANDEX_CLIENT_SECRET=
      - YANDEX_REDIRECT_URL=
      # - YOOKASSA_SHOP_ID=
      # - YOOKASSA_SECRET_KEY=
      - YOOKASSA_SHOP_ID=
      - YOOKASSA_SECRET_KEY=
    networks:
      - app-net

  db:
    image: postgres:15
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-net

  migrate:
    image: migrate/migrate:v4.15.2
    command:
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    networks:
      - app-net

volumes:
  pgdata:
networks:
  app-net:
