version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./uploads:/uploads
    expose:
      - "8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=appuser
      - DB_PASSWORD=apppass
      - DB_NAME=appdb
      - JWT_SECRET=supersecret123
    networks:
      - app-net

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - app-net

  migrate:
    image: migrate/migrate:v4.15.2
    command: -path=/migrations -database postgres://appuser:apppass@db:5432/appdb?sslmode=disable up
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    networks:
      - app-net

volumes:
  pgdata:
#  uploads:
networks:
  app-net:
